apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-client-k8s
    spring-boot: "true"
  name: ms-client-k8s-service
  namespace: spring-admin
spec:
  ports:
  - nodePort: 30008
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ms-client-k8s
  type: NodePort

